### ISSUE TITLE
Increase the number of surfaces for decoder task on small frame and high frame rate video.

### ISSUE THREAD

**Issue by SiewHoon** [01org/gstreamer-media-SDK#29]
Increase number of surfaces for decoder task with condition as below: 
i) width < 1281 
ii) height < 721
iii) frame rate > 50

**Comment by ph0b** [comment]
Hi,

in the issue, you state:
i) width > 1281
ii) height > 721

but it's the other way around in the commit: `info->Width < 1281 && info->Height < 721`
shouldn't it be `info->Width > 1281 && info->Height > 721` instead?

**Comment by ishmael1985** [comment]
I think it's better if you can provide the clip that would warrant such a special case of over-allocation so that we can try it out and figure out why this was done.

**Comment by ph0b** [comment]
+1 maybe increasing the number of surfaces could be done by tuning the async-depth instead, I think it'd be cleaner.

**Comment by ishmael1985** [comment]
Indeed, what I had in mind :) We can take it further by setting the mfxVideoParam::AsyncDepth dynamically, all we may need to do is check mfxVideoParam::mfx.MaxDecFrameBuffering after calling MFXVideoDECODE_DecodeHeader(). But without enough samples, we can't be too sure about this proposed solution.
