### ISSUE TITLE
using with windows 10 intel media sdk 

### ISSUE THREAD

**Issue by arpu** [01org/gstreamer-media-SDK#3]
Hello
my programm using gstreamer-vaapi on linux and i search for for multiplatform solution to
hardware decode mjpeg (jpeg) streams 

can i use this gstreamer plugin on windows 10?  i have no windows developer experience :/

**Comment by raj23** [comment]
Hi,

Currently this plugin is not supported in Windows yet. Only for Linux.

**Comment by arpu** [comment]
ok thx a lot for this information
so anyway technically it should be possible?

**Comment by raj23** [comment]
Yes. It should be possible.
