### ISSUE TITLE
Add checking for raw or mfx surface during update sink caps and set caps in mfxvpp

### ISSUE THREAD

**Issue by SiewHoon** [01org/gstreamer-media-SDK#37]
1. Add the checking for the raw or mfx surface during sinkpad update.
2.  Check for both sink and source caps changed during update.

**Comment by ishmael1985** [comment]
Can you help provide a test pipeline which demonstrates that it is possible for the memory types to switch during playing state, or maybe a hypothetical scenario in which this code snippet may come to effect?
