### ISSUE TITLE
video and goes out of sync 

### ISSUE THREAD

**Issue by bengji** [01org/gstreamer-media-SDK#4]
When transcoding a linear stream the video and audio goes out of sync after couple of hours.

this is the pipeline we used:
`gst-launch-1.0 souphttpsrc location="http://localhost:80/oranews_HD/mpegts" is-live=true ! tsdemux name=demux  ! queue max-size-buffers=1200 max-size-buffers=0 max-size-time=0 ! h264parse ! mfxh264dec ! mfxvpp width=1280 height=720 framerate=25/1 ! mfxh264enc rate-control=1 bitrate=1700 ! flvmux streamable=true name=mux ! rtmpsink location="rtmp://localhost:1935/pushrtmp/mfxtesasfht1s live=1" demux. ! queue max-size-buffers=1200 max-size-buffers=0 max-size-time=0 ! mpegaudioparse ! queue ! avdec_mp2float plc=true ! audioconvert ! queue ! voaacenc bitrate=128000 ! mux.`

We also tried using avdec_h264 instead of mfxh264dec and there is no out of sync issue so there must be something wrong with mfxh264dec.

**Comment by rislim** [comment]
Hi Bengji, 
Thank you for reported this issue at here. We will replicate it and debug on it.

**Comment by rislim** [comment]
Hi Benji,
May I know which gstreamer-framework version that you are using?

**Comment by bengji** [comment]
hi,
I'm using GStreamer 1.10.4

**Comment by SiewHoon** [comment]
Please check on Fixes #21 or using the latest code base. Please check the issue still able to reproduce or your side or not.

**Comment by bengji** [comment]
Thanks @rislim we will give it a try and keep you posted if the issue was fixed.

**Comment by bengji** [comment]
hi SivewHoon, we tested for few days, I want to confirm that the issue has been fixed. 
I'm going to go ahead and close this issue.
Thank You for the great work
