### ISSUE TITLE
Added AVC stream-format support in H264 

### ISSUE THREAD

**Issue by SiewHoon** [01org/gstreamer-media-SDK#41]
Added the H264 supported input AVC stream-format.

**Comment by ishmael1985** [comment]
Not sure what you are trying to achieve here. mfxdecode will force caps negotiation of byte-stream format with h264parse / h265parse, so unless you can prove an exceptional case as to why this code is to be included, I don't see why this commit is here.

**Comment by SiewHoon** [comment]
You didn't see it, does not mean it does not exists. If it does not exist why we want to add this code? This code fixed have to add in.

**Comment by ishmael1985** [comment]
We need proof of a plausible scenario whereby h264 avc formats somehow get negotiated with mfxh264dec. MSDK's H264 decoder can only accept the byte-stream format, with avc you'll get nothing. That where h264parse comes in, to convert h264 avc formats commonly found in containers such as Quicktime or Matroska, into elementary (byte-stream) format.
If such a scenario can happen, it's best to fix it at the parsing layer, or better yet, code in an internal parser for mfxdecode. The latter takes some development time and would be redundant actually with the existence of h264parse. Just detecting the avc format in mfxdecode won't solve the problem, you will definitely get some decoding errors without converting to byte stream.

**Comment by SiewHoon** [comment]
If you insist this code fixed does not need, I will provide you the video clip to replicate it, you can go and fix it. And submit the fixed to us. We will welcome to accept your fixed.

**Comment by ishmael1985** [comment]
It would be great if you can share the clip here :)

**Comment by ishmael1985** [comment]
It should be noted that this is an h264parse issue which has been since resolved in GStreamer release version 1.13.1 with the following patch:

https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/patch/gst/videoparsers/gsth265parse.c?id=93d29e80300f566b7a8e7d86beecb578fe03821c
