### ISSUE TITLE
Error initializing internal MFX session

### ISSUE THREAD

**Issue by pauldotknopf** [01org/gstreamer-media-SDK#42]
I am getting this error when running any of the mfx elements.

```
ERROR                    mfx gstmfxtaskaggregator.c:150:gst_mfx_task_aggregator_create_session: Error initializing internal MFX session
```

Here is my ```vainfo```.

```
libva info: VA-API version 0.99.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.99 (libva 1.67.0.pre1)
vainfo: Driver version: 16.7.3.64751-ubit
vainfo: Supported profile and entrypoints
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointEncFEIIntel
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointEncFEIIntel
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointEncFEIIntel
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : <unknown entrypoint>
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStatisticsIntel
```

I am using github.com/01org/iotg-lin-gfx-libva at ```9430287e9e1563777e3d51ba730636e78ed10796```
I am using github.com/01org/iotg-lin-gfx-libdrm at ```release/mr3```
msdk 16.7
msdk-media 16.7.3

**Comment by ishmael1985** [comment]
Are you certain you are running on a supported kernel version? What's the kernel version you are using?
A custom compiled kernel is required to run Intel MSDK on Linux.
Try running sample_decode / sample_multitranscode on your side to verify everything works.
Also please make sure to get the latest source from my repo:

https://github.com/ishmael1985/gstreamer-media-SDK

Once you verify the issue on your side to be fixed, you should close this case.

**Comment by pauldotknopf** [comment]
```
> uname -a
Linux intel-corei7-64 4.9.30-intel-pk-standard #1 SMP PREEMPT Sat Aug 26 18:23:48 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

The kernel is from here.

```
KBRANCH = "base"
SRCREV_machine ?= "22a3e397584619839ec645c7378dc40bdd5ad2d1"
SRCREV_meta ?= "299f12a06ca1d6fd90b24450dae3b9f257a536be"

SRC_URI = "git://github.com/01org/linux-intel-4.9.git;protocol=https;name=machine;branch=${KBRANCH}; \
           git://git.yoctoproject.org/yocto-kernel-cache;type=kmeta;name=meta;branch=yocto-4.9;destsuffix=${KMETA}"

LINUX_VERSION ?= "4.9.30"
LINUX_VERSION_EXTENSION = "-intel-pk-${LINUX_KERNEL_TYPE}"
```

Maybe there is a kernel config value missing?

**Comment by pauldotknopf** [comment]
Here is my kernel config.

https://gist.github.com/pauldotknopf/df7a6e703cd7c7c21dc577d04d9e69e5

I am testing samples now.

**Comment by ishmael1985** [comment]
Most likely missing patches from the kernel. You should use the officially supported Yocto version for APL.

https://software.intel.com/en-us/media-sdk/choose-download/embedded-iot

This official version uses 4.1.27. You should ensure that your kernel version matches with this and that patches have been  applied.

**Comment by lubagov** [comment]
In media_server_studio_getting_started_guide.pdf has guide how to build kernel. In MSD 2017 it it for 4.4 version. Work fine in Ubuntu 16.10/16.04 and CentOS.
First i build 4.7 version for OpenCL, with patches for OpenCL but it is not working, and 2 day too have problem to run...

**Comment by pauldotknopf** [comment]
I ran the bitbake for a supported configuration (following the guidance documents), and it worked. The only difference between the supported configuration and my custom configuration was the kernel. I will try to backport my solution to 4.1, and let you know the results.

Until then, I am going to consider this issue resolved. There is some encoding artifacts, but I will create a separate issue for that.

Thanks!
