### ISSUE TITLE
Artifacts while encoding

### ISSUE THREAD

**Issue by pauldotknopf** [01org/gstreamer-media-SDK#43]
I ran the following command:
```
gst-launch-1.0 -e videotestsrc pattern=18 ! queue ! mfxh264enc ! queue ! mpegtsmux ! filesink location=4k.mp4
```
When playing back the video, I am getting artifacts.

[video.mp4.zip](https://github.com/01org/gstreamer-media-SDK/files/1347241/video.mp4.zip)

Are the some encoder properties I could tweak with to fix this problem?

I am using a 7th gen i7. More info [here](http://termbin.com/bsnx5).

```
> vainfo
libva info: VA-API version 0.99.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.99 (libva 1.67.0.pre1)
vainfo: Driver version: 16.7.3.64751-ubit
vainfo: Supported profile and entrypoints
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointEncFEIIntel
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointEncFEIIntel
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointEncFEIIntel
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : <unknown entrypoint>
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStatisticsIntel
```

**Comment by ishmael1985** [comment]
I'm surprised that Intel MSS or MSDK for Linux even worked for Kabylake. The Yocto Embedded Edition specifically is for the Apollo Lake platform.

https://software.intel.com/en-us/forums/intel-media-sdk/topic/735307

**Comment by pauldotknopf** [comment]
Hmm..

Well, it did :) Throughput is amazing.

I am going to put a 6th gen CPU in and see if I see the same artifacts.

**Comment by ishmael1985** [comment]
Cool. Please let me know what you get and do ensure you get the latest source from my repo.

**Comment by pauldotknopf** [comment]
>  latest source from my repo

I was using the commit that intel provided via their "meta-intel-msdk" layer. I will update pointer.

**Comment by ishmael1985** [comment]
That version is a few months outdated, but anyway try and see if you can actually set it up on Yocto since there's a meson dependency.
That said, I ran the said pipeline and encountered no issues.

**Comment by pauldotknopf** [comment]
Working on it now.

Side question. The i965 solution did not give me enough throughput. I am trying to encode 4k60fps. On Windows, I can, and with iHD I *kind of* (minus artifacts) can. Is there no officially supported configuration on Linux that would give me 4k60fps?

**Comment by ishmael1985** [comment]
Well.... iHD has always been faster than i965 due to proprietary optimizations (and that gst-mfx was also optimized and well-written by yours truly and fellow accomplices :) ). On Linux, you just have to make sure you are running on a supported platform (Haswell, Broadwell, Skylake and Apollolake variants).

**Comment by pauldotknopf** [comment]
Well, after simply swapping the CPU, encoding works perfectly.

That is a bummer. The 7th-gen finally increased GPU performance, and we can't use it!

The fact that on Windows you can use old driver to encode on 7th gen Intel tells me that they have some kind of compatible API internally, hence why encoding works (almost) on Linux.

Intel, WHYYY!!!

**Comment by ishmael1985** [comment]
Well, yeah it's a big bummer. KBL's GPU has native 10-bit HEVC decode / encode support, VP9 10-bit decode, faster, more power-efficient, etc.
I can't speak for Intel since I'm not working for them anymore, but features such as KBL support need to be driven primarily by business need. Well, you'd better hope there's a good samaritan out there who can help with the situation, I can only work up to the GStreamer application layer.
